// Code generated by bpf2go; DO NOT EDIT.
//go:build (386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm) && linux

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type attrprogFlowKey struct {
	_      structs.HostLayout
	Pid    uint32
	Dport  uint16
	Family uint8
	Proto  uint8
	Daddr  [16]uint8
}

type attrprogFlowStat struct {
	_        structs.HostLayout
	BytesOut uint64
	BytesIn  uint64
	Comm     [16]uint8
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	attrprogMapFlows           = "flows"
	attrprogProgSkbConsumeUdp  = "skb_consume_udp"
	attrprogProgTcpCleanupRbuf = "tcp_cleanup_rbuf"
	attrprogProgTcpSendmsg     = "tcp_sendmsg"
	attrprogProgUdpSendmsg     = "udp_sendmsg"
)

// loadAttrprog returns the embedded CollectionSpec for attrprog.
func loadAttrprog() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_AttrprogBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load attrprog: %w", err)
	}

	return spec, err
}

// loadAttrprogObjects loads attrprog and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*attrprogObjects
//	*attrprogPrograms
//	*attrprogMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadAttrprogObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadAttrprog()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// attrprogSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type attrprogSpecs struct {
	attrprogProgramSpecs
	attrprogMapSpecs
	attrprogVariableSpecs
}

// attrprogProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type attrprogProgramSpecs struct {
	SkbConsumeUdp  *ebpf.ProgramSpec `ebpf:"skb_consume_udp"`
	TcpCleanupRbuf *ebpf.ProgramSpec `ebpf:"tcp_cleanup_rbuf"`
	TcpSendmsg     *ebpf.ProgramSpec `ebpf:"tcp_sendmsg"`
	UdpSendmsg     *ebpf.ProgramSpec `ebpf:"udp_sendmsg"`
}

// attrprogMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type attrprogMapSpecs struct {
	Flows *ebpf.MapSpec `ebpf:"flows"`
}

// attrprogVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type attrprogVariableSpecs struct {
}

// attrprogObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadAttrprogObjects or ebpf.CollectionSpec.LoadAndAssign.
type attrprogObjects struct {
	attrprogPrograms
	attrprogMaps
	attrprogVariables
}

func (o *attrprogObjects) Close() error {
	return _AttrprogClose(
		&o.attrprogPrograms,
		&o.attrprogMaps,
	)
}

// attrprogMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadAttrprogObjects or ebpf.CollectionSpec.LoadAndAssign.
type attrprogMaps struct {
	Flows *ebpf.Map `ebpf:"flows"`
}

func (m *attrprogMaps) Close() error {
	return _AttrprogClose(
		m.Flows,
	)
}

// attrprogVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadAttrprogObjects or ebpf.CollectionSpec.LoadAndAssign.
type attrprogVariables struct {
}

// attrprogPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadAttrprogObjects or ebpf.CollectionSpec.LoadAndAssign.
type attrprogPrograms struct {
	SkbConsumeUdp  *ebpf.Program `ebpf:"skb_consume_udp"`
	TcpCleanupRbuf *ebpf.Program `ebpf:"tcp_cleanup_rbuf"`
	TcpSendmsg     *ebpf.Program `ebpf:"tcp_sendmsg"`
	UdpSendmsg     *ebpf.Program `ebpf:"udp_sendmsg"`
}

func (p *attrprogPrograms) Close() error {
	return _AttrprogClose(
		p.SkbConsumeUdp,
		p.TcpCleanupRbuf,
		p.TcpSendmsg,
		p.UdpSendmsg,
	)
}

func _AttrprogClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed attrprog_bpfel.o
var _AttrprogBytes []byte
